version: '3.8'
services:
  nodejs-api:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./.env
    ports:
      - "3000:3000"
    container_name: envixi_rest_api
    links:
      - mongo-db
  mongo-db:
    image: mongo:5.0.9
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - "27017:27017"
    container_name: mongo-db
    volumes:
      - ./db/:/data/db
